"""ATTENTION!!!
This is autogenerated file. Please change it
only in case if you know what you are doing
"""
import base64
import contextlib
import logging
import os
import shutil
import sys
import tempfile
import zlib
import subprocess


VENV_FOLDER = 'venv'
VENV_PYTHON = os.path.join(
    os.path.abspath(VENV_FOLDER),
    'Scripts' if sys.platform == 'win32' else 'bin',
    'python'
)
VENV_BOOT_DATA = """eNrFVUuP2zYQvutXsMhBkuNwNxv0EmCLpoFTGCgcI5ukCBYLgZZGNhOKZMmR
Y/XXd0hZj2ydFj3VF3M4w5lvvnmodqZhRVG32DooCiYbaxwy66RGutUlSqOTOliVRiOcUMndYFUq46Xe
LwdVI7TYg0vOauOHk4Ph5LvxEoWrpRo1CI2dy/7QolSj5Kdju7POlOB9gq57mTD6RYCtUwTuZkBHorGg
J/0dUlb79dvBYJATOJVgka3j9co54/7mlTv4owWP33UuzaD6pUPwFEX4KUKy/bRdFx9Xm4/F9tWvK3bL
0gOi9S+vrmxnJbcdHozmxu2jfHWUDluhQB/TZL1Zv1+/+q2gx+Gd7Z7R9XWaJEmJJ7ohanjpQCAUFdSi
VVic65HlwYSXByi/FAfjUYsG6MUboTxE1RGcrLuiMRWcPb1evXtfbN5uVuT/50d1JfdUysYcxU5BEQpW
SZflPVlUzj0geRkKyZsvVTgTiqDvJKjqbBUv+gJz16ADyHpFTlGfMC+0xI5F3ImsqZG4FXjgcJIefTYj
JGfGsQGBE9IDe9dqlA3EMmYpUcUIJJRoXMeEIp6qjvWO0jwBRe6J5oz6khOCY85+Ys+Z0NXjoIPB/fOH
fwjngSirmEfii/1LbEq0BiwP7BgMqaGSrxIPw1Bl5w7Lvu2ccdZuqXx5HprMgbc9IllHgRORJVU0y9kP
t+zm+rrXfg/z787ofXxoNCkJL8gj9F297bbrtK9fRbALAkUV3hgNfecT+0pqYFLPYIRfQ2aOWkBQgtku
5Yss9jtfTJ3NF1Rzvv8z54um+pEv0mX0lY8+KB2aK8+0wRhy8v4IT8P3zrTWZ/n99UNomFFHr6eXl5Kf
4MRHMVZtWl2lfSu+6Ss0WY20XK7WEJlX0JfgfyyYQBGrQAFC62V9Rh800Z6clcOCyoKc9yldmPCAOggF
ST22b5I/b3IeGQgns/t8Gz3Gl+E0ZRQkGip0okShVDb47UGHWShsR9CG+ftspM7G14P1crwhO0WkB5yj
K2qDyWBWY9qzabwnKsLfE/Y6Lk6Gh9DDEqVQYWz7/TR+Z84btAxw4yKAE5QtBo6WA+Ilm6+lON13s2WQ
XNozPSk7qYvaqApcWO8kpaEvgqFVAmnEmtAV6VepX9ykDGh1s/SudNLSFplzFr4gj3mbYVrOAi3DZyTY
n1vlcqr3M8fLB/aUpc8aZqUlpnwo3WwsUu6tkvTB+c/+Lvggzf1s3S4f8gvfiznbfwG7XeXS
"""


@contextlib.contextmanager
def removable_tempdir():
    target = tempfile.mkdtemp()
    yield target
    shutil.rmtree(target)


def main(executable, *args):
    if os.path.exists(VENV_FOLDER) and '--renew' in args:
        shutil.rmtree(VENV_FOLDER)

    if not os.path.exists(VENV_FOLDER):
        with removable_tempdir() as temp_dir:
            venv_boot_filename = os.path.join(temp_dir, 'venv-boot.py')
            data = base64.b64decode(VENV_BOOT_DATA)
            data = zlib.decompress(data)
            with open(venv_boot_filename, 'wb') as venv_boot_file:
                venv_boot_file.write(data)

            subprocess.check_call((
                sys.executable,
                venv_boot_filename,
                VENV_FOLDER
            ))

        try:
            post_create()
        except:
            logging.exception('post create code failed')
            shutil.rmtree(VENV_FOLDER, ignore_errors=True)


def post_create():
    import subprocess
    VENV_PYTHON = globals().get('VENV_PYTHON', 'python')
    URL = 'git+https://github.com/apatrushev/get-venv-builder'
    subprocess.check_call([VENV_PYTHON,] + '-m pip install'.split() + [URL,])
    pass


if __name__ == '__main__':
    main(*sys.argv)
