"""ATTENTION!!!
This is autogenerated file. Please change it
only in case if you know what you are doing
cmd: gvb --post-code examples/self.py --output bootstrap.py
"""
import base64
import contextlib
import logging
import os
import shutil
import sys
import tempfile
import zlib
import subprocess


VENV_FOLDER = os.environ.get('VENV_FOLDER', 'venv')
VENV_PYTHON = os.path.join(
    os.path.abspath(VENV_FOLDER),
    'Scripts' if sys.platform == 'win32' else 'bin',
    'python'
)
VENV_BOOT_DATA = """eNrFVd+P2zYMfvdfobUPtrNUubsCG1YsxbriOgQY0qDXdRgOB0Ox6URXW9Ik
OY3315eSLdt3dffjaX4wRJEiP36kqFLLmmRZ2dhGQ5YRXiupLVGaC4u7Irdciqh0VrkUFs624vtglVfS
cHFYBlXNBDuAjnr1oZL7sJYmrDSElWmHTct0yatBY6FWU9kcG8urQTLjstkrLXMwJrK6fRER/DzYRlcI
9CogRVEqEKP+xmKGh83bYBDkCM45KEs2fvtaa6m/8Eo1/NmAsV91zmVQ/dxaMBiFmTFCtPtjt8k+XG8/
ZLtXv1yTNYmP1irzYrVSreJU6sMKk7qH3K5OXNuGVSBOq8vv6Pf0h1Ucbbab95tXv2bowJ1V7TNUX8RR
FOX2jDtID801MAtZASVrKpv19UlSZ0LzI+Qfs6M0VrAa8MQbVhnwqhNoXrZZLQvoPb2+fvc+277dXqP/
nx7VGd1jOWt5YvsKMle0gusk7QjDkh7AopdQTFp/LNwaUTh9y6Eqeiu/0RWZ6tpqgKRTpBj1KTFMcNsS
jzviJTYTVcweKZy5sSaZEJISqUlAoBk3QN41wvIafCmTGKkiCBK5lbolrEKeipZ0juI0ggrdI90J9iZF
BKeUvCSXhInicdBgcHt59zfhDCBlBTEW+SL/EBsTLcHmR3JyhthU0Sduj+GSJX2XJQ+7Z7h7ayxfmrpG
02BUh4iXXqBIZI4VTVLyzZpcXVx02q9h/l1LcfAHpUAl4gV+gq6zd+1uE3f1KxB2hqCwwlspoOt+ZL/i
AggXExjuq9FMYwswTDDZx3TxIyNHDeX6CV0kvv3pYmx2usDy08Nf6ZOXdBEvvc908IVp4R0zREjrQ49R
HuGq6UHLRpkkvb24c40z6PD0eHKOhBGLP+RjlbIRRdy15JuuUqPVQM981UJkWkBXiv+xcMwyXw0M4Fow
6TL6TSDnUa8MwypxctqlNHPTHWonZCh12B4k30916hlwK7m/X3uP/qRbjRk5CS+X1Sy3rKqS4BfRObW7
FJlqEZt7Vqj7JeFK3ksuksFROLgcdmLsoVGYtJlqY7+fpoF2V+c+1Ajt38eej/8FhvmNGWATcCOIfuV6
2muektd+3BN7dDePW84qN2y6qTq8kP3czx25fnzBGfLGuooug88lmQ5TP5NuJiMsmpuOHU97LrJSVgVo
9yihFDs6naGqmMXBULsejj9x8fwqJoAPDolvcs0Vzr5pfvYoBXp4QO8E03ISaOkeP2ffN/Z8qrcTx8s7
8i2Jn9VEcYVMGddok0scU6Mqjs/kf/Y34wM1t5NHYnmXzrxyU7Y/A8U3FSQ=
"""


@contextlib.contextmanager
def removable_tempdir():
    target = tempfile.mkdtemp()
    yield target
    shutil.rmtree(target)


def main(executable, *args):
    if os.path.exists(VENV_FOLDER) and '--renew' in args:
        shutil.rmtree(VENV_FOLDER)

    if not os.path.exists(VENV_FOLDER):
        with removable_tempdir() as temp_dir:
            venv_boot_filename = os.path.join(temp_dir, 'venv-boot.py')
            data = base64.b64decode(VENV_BOOT_DATA)
            data = zlib.decompress(data)
            with open(venv_boot_filename, 'wb') as venv_boot_file:
                venv_boot_file.write(data)

            subprocess.check_call((
                sys.executable,
                venv_boot_filename,
                VENV_FOLDER
            ))

        try:
            post_create()
        except:
            logging.exception('post create code failed')
            shutil.rmtree(VENV_FOLDER, ignore_errors=True)


def post_create():
    import subprocess
    VENV_PYTHON = globals().get('VENV_PYTHON', 'python')
    URL = 'git+https://github.com/apatrushev/get-venv-builder'
    subprocess.check_call([VENV_PYTHON,] + '-m pip install'.split() + [URL,])
    pass


if __name__ == '__main__':
    main(*sys.argv)
